[platformio]
default_envs = BOARD_VIEWE_UEDX80480070E_WB_A

;
; Here are the global configurations used for all board envs
;
[env]
framework = arduino
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
platform = espressif32
;platform_packages =
;    framework-arduinoespressif32 @ https://github.com/VIEWESMART/arduino-esp32.git
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.psram = auto
lib_compat_mode = strict
lib_ldf_mode = chain
lib_ignore =
    WebServer
lib_deps =
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    ArduinoJson
	zinggjm/GxEPD2@^1.3.6
    bodmer/TJpg_Decoder
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.0
    https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.2.0
    https://github.com/lvgl/LVGL.git#v8.4.0

;
; Here are the options that can be used in the board envs
;
[common]
build_flags =
; Arduino related:
    -DCORE_DEBUG_LEVEL=1    ; Set to `5` for full debug output, `0` for none
; LVGL related:
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
; Include path:
    -I src
; Others:
    ; -DDISABLE_ALL_LIBRARY_WARNINGS    ; Disable all library warnings

[spi_qspi_lcd]
build_flags =
; LVGL related:
    -DLV_COLOR_16_SWAP=1

[rgb_mipi_lcd]
build_flags =
; LVGL related:
    -DLV_COLOR_16_SWAP=0

; VIEWE boards:
[env:BOARD_VIEWE_UEDX80480070E_WB_A]
build_flags =
    ${common.build_flags}
    ${rgb_mipi_lcd.build_flags}
    -DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
    -DBOARD_VIEWE_UEDX80480070E_WB_A
    -D ASYNC_TCP_SSL_ENABLED=0
	-D MZOTA_USE_ASYNC_WEBSERVER=1
board = BOARD_VIEWE_UEDX80480070E_WB_A
